# Use root/example as user/password credentials
version: '3.1'

services:

  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - 4510:4510
      - 4511:4511
      - 4512:4512
      - 4513:4513
      - 4514:4514
      - 4515:4515
      - 4516:4516
      - 4517:4517
      - 4518:4518
      - 4519:4519
      - 4520:4520
      - 4521:4521
      - 4522:4522
      - 4523:4523
      - 4524:4524
      - 4525:4525
      - 4526:4526
      - 4527:4527
      - 4528:4528
      - 4529:4529
      - 4530:4530
      - 4531:4531
      - 4532:4532
      - 4533:4533
      - 4534:4534
      - 4535:4535
      - 4536:4536
      - 4537:4537
      - 4538:4538
      - 4539:4539
      - 4540:4540
      - 4541:4541
      - 4542:4542
      - 4543:4543
      - 4544:4544
      - 4545:4545
      - 4546:4546
      - 4547:4547
      - 4548:4548
      - 4549:4549
      - 4550:4550
      - 4551:4551
      - 4552:4552
      - 4553:4553
      - 4554:4554
      - 4555:4555
      - 4556:4556
      - 4557:4557
      - 4558:4558
      - 4559:4559
      - 4566:4566
      - 5678:5678
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      DEBUG: ${DEBUG:-1}
      DEFAULT_REGION: ap-northeast-1
      DOCKER_HOST: unix:///var/run/docker.sock
      DATA_DIR: ${DATA_DIR-}
      LAMBDA_EXECUTOR: ${LAMBDA_EXECUTOR:-local}
      LS_LOG: WARN
      HOST_TMP_FOLDER: ${TMPDIR:-/tmp/}localstack
      HOSTNAME: localstack
      HOSTNAME_EXTERNAL: localstack
      USE_SINGLE_REGION: 1
      USER: localstack
    volumes:
      - localstack_data:/tmp/localstack
    working_dir: /opt/code/localstack
    networks:
      - default


  glue:
    container_name: glue3
    image: amazon/aws-glue-libs:glue_libs_4.0.0_image_01
    ports:
      - 8080:8080
      - 18080:18080
      - 4040:4040
      - 8443:8443
      - 8888:8888
      - 8998:8998
    environment:
      PYSPARK_PYTHON: python3
      SPARK_CONF_DIR: /home/glue_user/spark/conf
      PYSPARK_PYTHON_DRIVER: python3
      LIVY_INTEGRATION_TEST: true
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      SPARK_HOME: /home/glue_user/spark
      PYTHONPATH: /home/glue_user/aws-glue-libs/PyGlue.zip:/home/glue_user/spark/python/lib/py4j-0.10.9-src.zip:/home/glue_user/spark/python/
      HADOOP_CONF_DIR: /home/glue_user/spark/conf
      LD_LIBRARY_PATH: /home/glue_user/native_libs/amd64/hadoop-lzo-native:/home/glue_user/native_libs/amd64/hadoop-native/
      LOCALSTACK_HOSTNAME: localstack
      LOCALSTACK_PORT: 4566
    volumes:
      -  glue_libs_data:/tmp/glue-libs
    working_dir: /home/glue_user/workspace
    depends_on:
      - localstack
    networks:
      - default
    tty: true

volumes:
  localstack_data:
  glue_libs_data: